services:
  express: &express
    image: game-assets-marketplace-api
    build:
      context: .
    networks:
      - postgres-express
    depends_on:
      - postgres
    profiles: ["none"]

  express-dev:
    <<: *express
    build:
      target: dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules
    profiles: ["dev"]

  express-prd:
    <<: *express
    build:
      target: prd
    environment:
      - NODE_ENV=production
    networks:
      - nginx-express
    profiles: ["prd"]

  nginx:
    image: nginx:1.27-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express
    networks:
      - nginx-express
    profiles: ["prd"]

  postgres:
    image: postgres:17.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - postgres-express
    volumes:
      - postgres:/var/lib/postgresql/data
    profiles: ["dev", "prd", "test"]

networks:
  nginx-express:
  postgres-express:

volumes:
  postgres:
